### ISSUE TITLE
[bug] Putting folder in remote subdirectory results in error and local files deletion

### ISSUE THREAD

**Issue by NudistBeaaach** [p0dalirius/smbclient-ng#48]
When trying to push folder in remote subdirectory (after "cd") this results in an error :

Failed uploading 'tmp.tFx8yu4WGF//test.txt': SMB SessionError: STATUS_OBJECT_PATH_NOT_FOUND

And the local file gets deleted, here are some screenshots:

![image](https://github.com/p0dalirius/smbclient-ng/assets/57132297/feca3dd9-c408-4c91-baad-cd76ead21d79)
![image](https://github.com/p0dalirius/smbclient-ng/assets/57132297/3c1e3b3c-7f73-4e03-82e3-e41ed4be287b)

This error seems to be present only when putting file in remote subdirectory as the two first "put -r" worked.

**Comment by p0dalirius** [comment]
Hi,

Thank you for your issue. I could reproduce the issue and I found the root cause,

I have fixed it in d0be49cdbf454f55fecf1f4532e2eac90403705d, can you try again from the latest commit of the [main](https://github.com/p0dalirius/smbclient-ng/tree/main) branch and tell me if it works for you?

Best regards,

**Comment by NudistBeaaach** [comment]
> Hi,
> 
> Thank you for your issue. I could reproduce the issue and I found the root cause,
> 
> I have fixed it in [d0be49c](https://github.com/p0dalirius/smbclient-ng/commit/d0be49cdbf454f55fecf1f4532e2eac90403705d), can you try again from the latest commit of the [main](https://github.com/p0dalirius/smbclient-ng/tree/main) branch and tell me if it works for you?
> 
> Best regards,

The files are no longer removed but the recursive put still fails I made a pr #53 which would fix this (some minor change: the cwd was added twice in the remote mkdir which resulted in wrong path)
